id: id
#default: searchable
searchable: 
  default: _teim
  date: _dtim
  string: _teim
  text: _teim
  symbol: _sim
  integer: _iim
  long: _lim
  boolean: _bi
  float: _fim
  double: _dbim
displayable: _ssm
facetable: _sim
sortable: _ssort
unstemmed_searchable: _tim
